apiVersion: v1
data:
  jwt: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklpSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjJaWEp6YVc5dUlqb2lNUzR3SWl3aWJHbGpaVzV6WlY5cFpDSTZJbVJsYlc4aUxDSmpiSFZ6ZEdWeVgyTmhjR0ZqYVhSNUlqbzFNQ3dpWlhod0lqb3hOakU1TnprNU1URXpMQ0pwWVhRaU9qRTFPRGd3T1RBNU1EY3NJbWx6Y3lJNklrUXlhVkVzSUVsdVl5NGlMQ0p1WW1ZaU9qRTFPRGd3TWpnNE1UUXNJbk4xWWlJNkltUXlhWEVpZlEuUFFDTDZGR2g0Y2JNdmlYYURZcEFUVFRTcDRFS1dRY1lLNG8wTUVFYjVWWXQwSDNhUkdxU3dFdl9HZ294Tmk0SkdKYWV6ZDlLaUNEbVBSSjRiOGhKZTAzZlRoWGZMNWZXdGJuWThYTkhsS243aHVkUXpKZlhDNnU2Yjd2eUtmSHd1ZFQ4WlROVEZqQk9DMkM0bDh4Z3hZS3FjbWFHSUFFUkh3TG1ManBzRHlR
kind: Secret
metadata:
  name: license-secret
  namespace: kommander
type: Opaque
---
apiVersion: kommander.mesosphere.io/v1beta1
kind: License
metadata:
  name: license-se-demo
  namespace: kommander
spec:
  licenseRef:
      name: license-secret
